#!/bin/bash

set -ex

COMMIT_SHA=$(git rev-parse --short HEAD)
RELEASE_NAME="master-${COMMIT_SHA}.tar.gz"

cd "dist"
tar czf "../$RELEASE_NAME" .
cd ..
BUILD_SHA=$(shasum ${RELEASE_NAME} | cut -d " " -f1)
DOWNLOAD_URL=$(echo "https://downloads.mesosphere.io/dcos-ui/${RELEASE_NAME}")
FILENAME='buildinfo.json'

# cat config to artifact file
cat <<EOF > ${FILENAME}
{
  "single_source": {
    "kind": "url_extract",
    "url": "${DOWNLOAD_URL}",
    "sha1": "${BUILD_SHA}"
  }
}
EOF

# upload
aws s3 cp $RELEASE_NAME "s3://downloads.mesosphere.io/dcos-ui/$RELEASE_NAME
